/**
 * Resolve a vehicle color name to its approximate hex value.
 * Used when JSON data files contain color names without hex codes.
 *
 * Strategy:
 *  1. Exact / startsWith match against known brand color names
 *  2. Keyword-family detection (red, blue, black, white, etc.)
 *  3. Fallback → '#808080' (neutral grey)
 */

// ── Known specific color name → hex (Indian 2W brands) ────────────────────────
const SPECIFIC_COLORS: Record<string, string> = {
    // ── Hero MotoCorp ──────────────────────────────────────────────────
    'red black':                '#8B0000',
    'nobel red':                '#C00000',
    'black tornado grey':       '#3A3A3A',
    'black sparking blue':      '#003087',
    'matte grey':               '#7A7A7A',
    'black with greenish yellow': '#1A2A1A',
    'black heavy grey':         '#404040',
    'black with heavy grey':    '#404040',
    'heavy grey with black':    '#505050',
    'heavy grey':               '#606060',
    'heavy grey metallic':      '#5A5A5A',
    'black with green':         '#1A2A1A',
    'black leaf green':         '#1A2E1A',
    'black industrial grey':    '#3C3C3C',
    'black nexus blue':         '#002875',
    'black pearl red':          '#6B0000',
    'black smoke':              '#2C2C2C',
    'black teal red':           '#1C3A3A',
    'black with force silver':  '#3A3A3A',
    'black with forest blue':   '#1A2840',
    'black with polestar blue': '#1A2040',
    'black with red':           '#3A0000',
    'black with sports red':    '#6A0000',
    'black with techno blue':   '#1A2550',
    'black with tornado grey metallic': '#3A3A3A',
    'black red stripe':         '#3A0000',
    'black grey stripe':        '#404040',
    'black brown stripes':      '#3A2010',
    'black red purple':         '#3A0030',
    'black purple':             '#1A001A',
    'black and accent':         '#1A1A1A',
    'black monotone':           '#1A1A1A',
    'black metallic':           '#2A2A2A',
    'black metalic silver':     '#303030',
    'blk funk lime yellow':     '#3A4A00',
    'funk lime yellow':         '#BACC00',
    'funk lime yel grey':       '#8A9A00',
    'stealth black':            '#1A1A1A',
    'stealth gray':             '#2C2C2C',
    'panther black':            '#111111',
    'panther black metallic':   '#181818',
    'regal black':              '#0A0A0A',
    'matte black':              '#2C2C2C',
    'matt slate black':         '#252525',
    'mat steel black metallic': '#252525',
    'stallion black':           '#1A1A1A',
    'tar black':                '#1A1A1A',
    'phantom black':            '#111111',
    'cosmic black':             '#111111',
    'gloss black':              '#1A1A1A',
    'enigma black':             '#0A0A0A',
    'power black':              '#0A0A0A',
    // ── Bajaj ──────────────────────────────────────────────────────────
    'blazing red':              '#CC0000',
    'candy blazing red':        '#CC0000',
    'fiery red':                '#D62000',
    'sporting red':             '#CC0000',
    'sunset red':               '#E8400A',
    'canyon red':               '#C03000',
    'turbo red':                '#CC0000',
    'groovy red':               '#D00000',
    'sports red':               '#C80000',
    'sport red':                '#C80000',
    'black sports red':         '#6A0000',
    'sports red black':         '#6A0000',
    'black-sports red':         '#6A0000',
    'rebel red metallic':       '#A00000',
    'precious red metallic':    '#A00000',
    'eclipse red':              '#B00000',
    'radiant red metallic':     '#CC0020',
    'ruby metallic':            '#9C0020',
    'grand prix red':           '#CC0000',
    'fearless red':             '#D00000',
    'terra rossa':              '#B04030',
    'bordeaux red metallic':    '#6B0000',
    'imperial red':             '#A00000',
    // ── Honda ──────────────────────────────────────────────────────────
    'pearl horizon white':      '#F0F0EC',
    'pearl fadeless white':     '#F5F5F0',
    'pearl precious white':     '#F5F5F0',
    'pearl silver white':       '#E8E8E8',
    'pearl siren blue':         '#1E88D4',
    'pearl igneous black':      '#1A1A1A',
    'pearl deep ground gray':   '#4A4A4A',
    'pearl deep ground grey':   '#4A4A4A',
    'pearl deep ground gray emblem': '#4A4A4A',
    'pearl deep ground gray stripe': '#4A4A4A',
    'pearl deep ground gray with lemon ice yellow': '#4A4A4A',
    'pearl sports yellow':      '#F0C000',
    'pearl white':              '#F5F5F0',
    'pearl siren blue with athletic blue metallic': '#1E88D4',
    'pearl siren blue with lemon ice yellow': '#1E88D4',
    'pearl siren blue with sports red': '#1E88D4',
    'athletic blue metallic':   '#1E5CA8',
    'candy jazz blue':          '#1A6CA8',
    'gloss red':                '#CC0000',
    // ── Yamaha ─────────────────────────────────────────────────────────
    'techno blue':              '#0062CC',
    'techno blue matte black':  '#003080',
    'techno blue met blk':      '#003080',
    'nexus blue':               '#003087',
    'nexus blue white':         '#003087',
    'metallic nexus blue':      '#003087',
    'matt nexus blue':          '#003087',
    'polestar blue':            '#002B6B',
    'cobalt blue':              '#0047AB',
    'azure blue':               '#0080C8',
    'deep sea blue':            '#003366',
    'teal blue':                '#008080',
    'sparkle blue':             '#0066CC',
    'cosmic blue':              '#003399',
    'blue black':               '#001866',
    'blue with black':          '#001866',
    'ice cyan white':           '#E0F8F8',
    'matt axis grey':           '#7A7A7A',
    'matt axis grey metallic':  '#7A7A7A',
    'matte axis grey':          '#7A7A7A',
    'matte axis gray metallic': '#7A7A7A',
    'matte axis grey metallic': '#7A7A7A',
    'combat grey':              '#708090',
    'matte volcanic grey':      '#606060',
    'matte vernier grey':       '#787878',
    'matte gunpowder black metallic': '#2A2A2A',
    'mist grey':                '#B0B0B0',
    'ebony grey':               '#4A4A4A',
    'valor grey':               '#6A6A6A',
    'matt shadow grey':         '#5A5A5A',
    'matt grey':                '#7A7A7A',
    'matt gray':                '#7A7A7A',
    'matt metallic silver':     '#C0C0C0',
    'matt steel grey':          '#707070',
    'metalic matt grey':        '#7A7A7A',
    'matte rainforest green':   '#2E5A2E',
    'force silver':             '#C8C8C8',
    'force silver metallic':    '#C8C8C8',
    'shield gold':              '#D4A000',
    'matte shield gold':        '#C89400',
    'shield gold grey':         '#9A7A40',
    'iconic yellow':            '#F5C000',
    'daring yellow':            '#F5C800',
    'moon yellow':              '#F0C800',
    'vibrant orange':           '#FF6600',
    'canyon orange':            '#D05000',
    'abrax orange':             '#E05000',
    // ── Royal Enfield ──────────────────────────────────────────────────
    'muted madras':             '#8B6914',
    'copper brown':             '#8B4513',
    'hazel brown':              '#7B4A2A',
    'bold brown':               '#6A3A20',
    'matte brown':              '#7B4A2A',
    'grassland green':          '#3A7A3A',
    'forest green':             '#228B22',
    'green with black':         '#1A4A1A',
    'silver':                   '#C0C0C0',
    'chrome silver':            '#D0D0D0',
    'cloud silver':             '#D4D4D4',
    'alpine silver':            '#C8C8C8',
    'mercuric silver':          '#B8B8B8',
    'titanium metallic':        '#7A7A7A',
    'digital silver':           '#C0C0C0',
    'grey blue stripe':         '#607090',
    'aqua grey':                '#7A9090',
    'orchid purple metallic':   '#8A2B8A',
    'black with purple':        '#2A002A',
    'mystique magenta':         '#B02080',
    'solid maroon':             '#800000',
    'palace maroon':            '#700000',
    'matt pearl white':         '#F5F5F0',
    'matt giallo lime':         '#D4D800',
    'neon shooting star':       '#C0D400',
    'eternal white':            '#F5F5F5',
    'spotlight white':          '#F0F0EE',
    'mystic white':             '#F0F0EC',
    'glacier white':            '#EEF2F4',
    'arctic white':             '#F2F2F0',
    'cyber white':              '#F0F0EE',
    'stellar white':            '#F0F0EC',
    'summit white':             '#F5F5F0',
    'ivory white':              '#FFFFF0',
    'orange with black':        '#8A3800',
    'red smoke':                '#8B0000',
    'red with black':           '#6A0000',
    'gray with black':          '#404040',
    'grey with black':          '#404040',
    'celestial blue':           '#4169E1',
    'vibrant blue metallic':    '#1A52CC',
    'decent blue metallic':     '#2A5A8A',
    'teal':                     '#008080',
    'carbon black':             '#1A1A1A',
    'geny gray metallic':       '#7A7A7A',
    'electric yellow metallic': '#E8C800',
    'neptune blue':             '#1A5080',
    'black matshdow grey':      '#3A3A3A',
}

// ── Keyword family detection (ordered: most specific first) ───────────────────
const COLOR_KEYWORDS: Array<[string, string]> = [
    // Dark/Matte Black variants first
    ['matte black',   '#2C2C2C'],
    ['matt black',    '#2C2C2C'],
    ['gloss black',   '#1A1A1A'],
    ['stealth black', '#1A1A1A'],
    ['panther black', '#111111'],
    ['carbon black',  '#1A1A1A'],
    ['regal black',   '#0A0A0A'],
    // Color + Black combo (primary color wins)
    ['red black',     '#8B0000'],
    ['black red',     '#8B0000'],
    ['blue black',    '#001866'],
    ['black blue',    '#001866'],
    ['black grey',    '#404040'],
    ['grey black',    '#404040'],
    ['black silver',  '#404040'],
    ['black brown',   '#3A2010'],
    ['black green',   '#1A2E1A'],
    // Specific blues
    ['nexus blue',    '#003087'],
    ['techno blue',   '#0062CC'],
    ['polestar blue', '#002B6B'],
    ['cobalt blue',   '#0047AB'],
    ['siren blue',    '#1E88D4'],
    ['azure blue',    '#0080C8'],
    ['teal blue',     '#008080'],
    ['ocean blue',    '#1B6CA8'],
    ['sparkle blue',  '#0066CC'],
    ['deep.*blue',    '#003399'],
    ['athletic blue', '#1E5CA8'],
    // Specific reds
    ['blazing red',   '#CC0000'],
    ['sports red',    '#C80000'],
    ['sport red',     '#C80000'],
    ['grand prix red','#CC0000'],
    ['candy.*red',    '#CC0000'],
    ['rebel red',     '#A00000'],
    ['sunset red',    '#E8400A'],
    ['eclipse red',   '#B00000'],
    ['turbo red',     '#CC0000'],
    ['fiery red',     '#D62000'],
    ['fearless red',  '#D00000'],
    ['imperial red',  '#A00000'],
    ['bordeaux red',  '#6B0000'],
    // Specific whites
    ['pearl.*white',  '#F5F5F0'],
    ['arctic white',  '#F2F2F0'],
    ['glacier white', '#EEF2F4'],
    ['cyber white',   '#F0F0EE'],
    ['ivory white',   '#FFFFF0'],
    ['mystic white',  '#F0F0EC'],
    ['eternal white', '#F5F5F5'],
    ['stellar white', '#F0F0EC'],
    ['summit white',  '#F5F5F0'],
    // Specific greys
    ['axis gr',       '#7A7A7A'],
    ['matte gr',      '#6A6A6A'],
    ['matt gr',       '#7A7A7A'],
    ['heavy gr',      '#606060'],
    ['tornado gr',    '#5A5A5A'],
    ['combat gr',     '#708090'],
    ['volcanic gr',   '#606060'],
    ['industrial gr', '#3C3C3C'],
    ['ebony gr',      '#4A4A4A'],
    ['gunpowder',     '#2A2A2A'],
    ['aqua gr',       '#7A9090'],
    ['cloud silver',  '#D4D4D4'],
    ['chrome silver', '#D0D0D0'],
    ['force silver',  '#C8C8C8'],
    ['alpine silver', '#C8C8C8'],
    // Specific greens
    ['grassland gr',  '#3A7A3A'],
    ['forest gr',     '#228B22'],
    ['rainforest gr', '#2E5A2E'],
    ['leaf green',    '#3A8A3A'],
    // Specific yellows/golds
    ['shield gold',   '#D4A000'],
    ['iconic yellow', '#F5C000'],
    ['daring yellow', '#F5C800'],
    ['moon yellow',   '#F0C800'],
    ['lime yellow',   '#BACC00'],
    ['lime gr',       '#BACC00'],
    ['giallo',        '#D4D800'],
    ['electric yellow','#E8C800'],
    // Specific oranges
    ['abrax orange',  '#E05000'],
    ['canyon orange', '#D05000'],
    ['vibrant orange','#FF6600'],
    // Browns/Maroons
    ['copper brown',  '#8B4513'],
    ['hazel brown',   '#7B4A2A'],
    ['muted madras',  '#8B6914'],
    ['solid maroon',  '#800000'],
    ['palace maroon', '#700000'],
    ['bordeaux',      '#6B0000'],
    ['terra rossa',   '#B04030'],
    // Purples
    ['orchid purple', '#8A2B8A'],
    ['mystique magenta','#B02080'],
    ['magenta',       '#C02080'],
    ['purple',        '#8B008B'],
    // Generic families (last resort before fallback)
    ['black',         '#1A1A1A'],
    ['red',           '#CC0000'],
    ['blue',          '#1E88D4'],
    ['white',         '#F5F5F0'],
    ['silver',        '#C0C0C0'],
    ['grey',          '#808080'],
    ['gray',          '#808080'],
    ['gold',          '#D4A000'],
    ['yellow',        '#F5C000'],
    ['green',         '#228B22'],
    ['orange',        '#FF6600'],
    ['brown',         '#8B4513'],
    ['maroon',        '#800000'],
    ['purple',        '#8B008B'],
    ['teal',          '#008080'],
    ['pink',          '#FF69B4'],
]

/**
 * Resolve a vehicle color name to a hex string.
 * Returns `#808080` if no match can be found.
 */
export function resolveVehicleColorHex(name: string): string {
    if (!name) return '#808080'
    const lower = name.toLowerCase().trim()

    // 1. Exact match in specific table
    if (SPECIFIC_COLORS[lower]) return SPECIFIC_COLORS[lower]

    // 2. StartsWith match (handles trailing edition/variant suffixes)
    for (const [key, hex] of Object.entries(SPECIFIC_COLORS)) {
        if (lower.startsWith(key)) return hex
    }

    // 3. Keyword family detection (regex-based for wildcard patterns)
    for (const [keyword, hex] of COLOR_KEYWORDS) {
        const regex = new RegExp(keyword, 'i')
        if (regex.test(lower)) return hex
    }

    return '#808080'
}
